DROP DATABASE mydb;
CREATE DATABASE IF NOT EXISTS mydb;
CREATE TABLE IF NOT EXISTS `mydb`.`Batting` (
  `A_ID` INT NOT NULL AUTO_INCREMENT,
  `A_NAME` VARCHAR(100) NULL,
  `A_COUNTRY` INT NULL,
  `A_OPPOSITION` INT NULL,
  `A_RUNS` INT NULL,
  `A_MINS` INT NULL,
  `A_BALLSFACED` INT NULL,
  `A_FOURS` INT NULL,
  `A_SIXES` INT NULL,
  `A_STRIKERATE` DOUBLE NULL,
  `A_INNINGS` INT NULL,
  `A_GROUND` INT NULL,
  `A_DATE` DATE NULL,
  PRIMARY KEY (`A_ID`));

CREATE TABLE IF NOT EXISTS `mydb`.`Matches` (
  `M_ID` INT NOT NULL AUTO_INCREMENT,
  `M_HOMENAME` VARCHAR(100) NULL,
  `M_HOMENUM` INT NULL,
  `M_OPPNAME` VARCHAR(100) NULL,
  `M_OPPNUM` INT NULL,
  `M_HOMESCORE` DOUBLE NULL,
  `M_OPPSCORE` DOUBLE NULL,
  `M_DAYNIGHT` INT NULL,
  `M_BATFIRST` TINYINT(1) NULL,
  `M_TOSSWON` TINYINT(1) NULL,
  `M_NEUTRAL` TINYINT(1) NULL,
  `M_GROUNDNAME` VARCHAR(100) NULL,
  `M_GROUNDNUM` INT NULL,
  `M_DATE` DATE NULL,
  `M_RPO` DOUBLE NULL,
  `M_RESULT` TINYINT(1) NULL,
  PRIMARY KEY (`M_ID`));

CREATE TABLE IF NOT EXISTS `mydb`.`Bowling` (
  `O_ID` INT NOT NULL AUTO_INCREMENT,
  `O_NAME` VARCHAR(100) NULL,
  `O_OVERS` INT NULL,
  `O_MAIDENS` INT NULL,
  `O_RUNS` INT NULL,
  `O_WICKETS` INT NULL,
  `O_ECONOMY` DOUBLE NULL,
  `O_INNINGS` INT NULL,
  `O_OPPOSITION` INT NULL,
  `O_GROUND` INT NULL,
  `O_DATE` DATE NULL,
  PRIMARY KEY (`O_ID`));
