SELECT M_HOMENUM, M_OPPNUM, M_RESULT, M_TOSSWON, M_BATFIRST, M_GROUNDNUM, M_DATE, M_DAYNIGHT, M_NEUTRAL, STRENGTH
FROM Matches, benchstrength
WHERE NEWID = M_ID
INTO OUTFILE 'C:/WHOLE_MATCHES.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

SELECT M_HOMENUM, M_OPPNUM, M_RESULT, M_TOSSWON, M_BATFIRST, M_GROUNDNUM, M_DATE, M_DAYNIGHT, M_NEUTRAL, STRENGTH
FROM Matches, benchstrength
WHERE NEWID = M_ID AND M_HOMENUM = 1 AND M_OPPNUM = 2
INTO OUTFILE 'C:/1_2_MATCHES.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

SELECT M_HOMENUM, M_OPPNUM, M_RESULT, M_TOSSWON, M_BATFIRST, M_GROUNDNUM, M_DATE, M_DAYNIGHT, M_NEUTRAL, STRENGTH
FROM Matches, benchstrength
WHERE NEWID = M_ID AND M_HOMENUM = 2 AND M_OPPNUM = 1
INTO OUTFILE 'C:/2_1_MATCHES.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';